theme: jekyll-theme-cayman
title: Effect of APOE Alleles on the Glial Transcriptome
description: Alberto Serrano-Pozo, Zhaozhi Li, Ayush Noori, Aziz Mezlini, Liang Li, Huong N. Nguyen, Rosemary J. Jackson, Bradley T. Hyman, Sudeshna Das
show_downloads: "true"
baseurl: /apoe-glia